# To build and launch (first time):
#   $ docker-compose up -d
# To create new images (--no-cache) to force building from scratch:
#   $ docker-compose build
# To launch again (leave out -d for non daemon launch):
#   $ docker-compose up -d
# To stop containers:
#  $ docker-compose stop
version: '3'
services:
  webgme:
    build: .
    depends_on:
      - mongo
    networks:
      - bridge
    environment:
      - NODE_ENV=devdep
      - MONGO_IP=mongo
    volumes:
      - $HOME/dockershare:/dockershare
    ports:
     # Change the LHS to map to other port on host
     - 8889:80
  mongo:
    image: mongo:3.4.1
    ports:
      - 27017:27017
    volumes:
      - $HOME/dockershare/db:/data/db
  webgme-dss-worker:
    build:
      context: .
      dockerfile: DockerfileJMod
    command: ["cat", "/dev/null"] # A no-op command so the image is built.
    networks:
      - bridge
    environment:
      - NODE_ENV=devdep